# Copyright 2025 Niels
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = format, lint, charm-static, charm-unit, charm-integration, app-unit, unit
min_version = 4.0.0

[vars]
charm_root = {tox_root}/charm
charm_src = {[vars]charm_root}/src
charm_tests = {[vars]charm_root}/tests
app_src = {tox_root}/app.py
app_tests = {tox_root}/tests

[testenv]
set_env =
    PY_COLORS=1
pass_env =
    PYTHONPATH
    CHARM_BUILD_DIR
    MODEL_SETTINGS
    STATUS_APP_CHARM_FILE
    STATUS_APP_ROCK_IMAGE
    STATUS_APP_BUILD_ARTIFACTS

[testenv:format]
description = Apply coding style standards to charm code
changedir = {[vars]charm_root}
deps =
    ruff
commands =
    ruff format {[vars]charm_src} {[vars]app_src}
    ruff check --fix {[vars]charm_src} {[vars]app_src}

[testenv:charm-format]
description = Alias for format
changedir = {[testenv:format]changedir}
deps = {[testenv:format]deps}
commands = {[testenv:format]commands}

[testenv:lint]
description = Check charm code against coding style standards
changedir = {[vars]charm_root}
deps =
    ruff
    codespell
commands =
    codespell {[vars]charm_root} {[vars]app_src}
    ruff check {[vars]charm_src} {[vars]app_src}
    ruff format --check --diff {[vars]charm_src} {[vars]app_src}

[testenv:charm-lint]
description = Alias for lint
changedir = {[testenv:lint]changedir}
deps = {[testenv:lint]deps}
commands = {[testenv:lint]commands}

[testenv:charm-unit]
description = Run charm unit tests
changedir = {[vars]charm_root}
set_env =
    PYTHONPATH = {[vars]charm_root}/lib:{[vars]charm_src}
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
deps =
    pytest
    coverage[toml]
    -r {[vars]charm_root}/requirements.txt
commands =
    coverage run --source={[vars]charm_src} \
                 -m pytest \
                 --tb native \
                 -v \
                 -s \
                 {posargs} \
                 {[vars]charm_tests}/unit
    coverage report

[testenv:charm-static]
description = Run charm static type checks
changedir = {[vars]charm_root}
deps =
    pyright
    -r {[vars]charm_root}/requirements.txt
commands =
    pyright {posargs}

[testenv:charm-integration]
description = Run charm integration tests
changedir = {[vars]charm_root}
deps =
    pytest
    juju
    jubilant
    pytest-operator
    -r {[vars]charm_root}/requirements.txt
commands =
    pytest -v \
           -s \
           --tb native \
           --log-cli-level=INFO \
           {posargs} \
           {[vars]charm_tests}/integration

[testenv:app-unit]
description = Run app unit tests
set_env =
    PYTHONPATH = {tox_root}
deps =
    pytest
    -r {tox_root}/requirements.txt
commands =
    pytest -v -s {posargs} {[vars]app_tests}

[testenv:unit]
description = Run app unit tests (alias for app-unit)
set_env =
    PYTHONPATH = {tox_root}
deps =
    pytest
    -r {tox_root}/requirements.txt
commands =
    pytest -v -s {posargs} {[vars]app_tests}
